### ISSUE TITLE
Use GitHub actions to assign tags to issues automatically

### ISSUE THREAD

**Issue by KOLANICH** [open-source-ideas/meta#11]
## Proposed change

GH Actions allow to trigger an action when an issue is added and then do something to it. Currently @FredrikAugust assigns the tags manually. It is proposed to create a script parsing the issues and assigning the needed tags.

## Proposed implementation

* In the repo a yaml file containing the description of sections and tags in it is stored.

```yaml:
- name: Complexity
  limit: 1 # the greatest count of the checkboxes to be selected. # If more than this amount is selected, first ones (in `allowed`) are kept.
  allowed: # only these tags are allowed.
    - Much Work
    - Little work
```

Repetition of the sections mentioned in the file is not allowed, in this case the issue is considered invalid.

* on each issue creation or first message update the bot checks the format. If the format is not satisfied, the issue is closed.
* it then synchronises GH tags with the tags described in the file.
